# Exercises

In [1]:
import numpy as np

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [5]:

# formula = weight / (height**2) * 730
height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

bmi = weight / (height **2) * 730
bmi



array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [27]:
"""
Example Result for make_matrix(0,15,(3,3)):
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def make_matrix(low,high,shape,data_type = float): -- Example
#     pass


def make_matrix(low, high, shape, dtype):
    return np.random.uniform(low, high, shape).astype(dtype)

make_matrix(1,100, (3,5), (np.int_))

array([[89, 98, 73, 25, 54],
       [22, 95, 48, 64, 65],
       [55, 37, 87, 58, 80]])

### #3 - Open and load the data for the Chicago White Sox hitting data for this past season.Create a function that will compare the infield players output vs the outfield players output vs *hybrid. (Infield - {C, 1B, 2B, SS, 3B, MI}, Outfield - {LF, CF, RF, OF}, *Hybrid - {DH, UT}) for a specific stat. i.e. BA or HR or OPS

*Hybrid is optional


In [28]:
import csv
import numpy as np

#Test to make sure you have the correct data



In [132]:


FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, 
                         invalid_raise = False, names = True, dtype = DATATYPES)
    return data

whitesox = load_data('whitesox_2021_hitting.csv')

homerun = whitesox['HR']
position = whitesox['Pos'].astype(np.str_)


infield = np.array(['C', '1B', '2B', '3B', 'SS', 'MI'])
outfield = np.array(['LF', 'CF', 'RF', 'OF'])


# infield_homerun = homerun[np.where(position == infield)]
# outfield_homerun = homerun[np.where('Pos' in outfield)]

print(homerun[np.where(position == "C")])
# print(position[infield])
# print(infield_homerun)




def find_comparison(stat):
    infield = np.average(whitesox[stat])
    outfield = np.average(whitesox[stat])
    if infield > outfield:
        return f'Infield players had a higher {stat} average({infield}) than Outfield({outfield})'
    else:
        return f'Outfield players had a better {stat} average({outfield}) than Infield({infield})'

find_comparison('HR')

[23  4  5]


'Outfield players had a better HR average(7.916666666666667) than Infield(7.916666666666667)'